In [3]:
from google.cloud import bigquery
import pandas as pd

/Users/tommy/.venv/lib/python3.10/site-packages/google/api_core/_python_version_support.py:254: FutureWarning: You are using a Python version (3.10.20) which Google will stop supporting in new releases of google.api_core once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.api_core past that date.
  warnings.warn(message, FutureWarning)
/Users/tommy/.venv/lib/python3.10/site-packages/google/api_core/_python_version_support.py:254: FutureWarning: You are using a Python version (3.10.20) which Google will stop supporting in new releases of google.cloud.bigquery once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.bigquery past that date.
  warnings.warn(message, FutureWarning)

### Hacker News

In [2]:
client = bigquery.Client(project='project-0ef0a780-55e5-435e-9d4')

In [3]:
dataset_ref = client.dataset('hacker_news', project="bigquery-public-data")

In [4]:
df = client.get_dataset(dataset_ref)

In [5]:
tables = list(client.list_tables(df))

In [6]:
for table in tables:
    print(table.table_id)

full

In [7]:
table_ref = dataset_ref.table("full")

In [8]:
table = client.get_table(table_ref)

In [9]:
table.schema

[SchemaField('title', 'STRING', 'NULLABLE', None, 'Story title', (), None, None),
 SchemaField('url', 'STRING', 'NULLABLE', None, 'Story url', (), None, None),
 SchemaField('text', 'STRING', 'NULLABLE', None, 'Story or comment text', (), None, None),
 SchemaField('dead', 'BOOLEAN', 'NULLABLE', None, 'Is dead?', (), None, None),
 SchemaField('by', 'STRING', 'NULLABLE', None, "The username of the item's author.", (), None, None),
 SchemaField('score', 'INTEGER', 'NULLABLE', None, 'Story score', (), None, None),
 SchemaField('time', 'INTEGER', 'NULLABLE', None, 'Unix time', (), None, None),
 SchemaField('timestamp', 'TIMESTAMP', 'NULLABLE', None, 'Timestamp for the unix time', (), None, None),
 SchemaField('type', 'STRING', 'NULLABLE', None, 'type of details (comment comment_ranking poll story job pollopt)', (), None, None),
 SchemaField('id', 'INTEGER', 'NULLABLE', None, "The item's unique id.", (), None, None),
 SchemaField('parent', 'INTEGER', 'NULLABLE', None, 'Parent comment ID', (), None, None),
 SchemaField('descendants', 'INTEGER', 'NULLABLE', None, 'Number of story or poll descendants', (), None, None),
 SchemaField('ranking', 'INTEGER', 'NULLABLE', None, 'Comment ranking', (), None, None),
 SchemaField('deleted', 'BOOLEAN', 'NULLABLE', None, 'Is deleted?', (), None, None)]

In [10]:
data = client.list_rows(table, max_results=5).to_dataframe()

In [11]:
data

,title,url,text,dead,by,score,time,timestamp,type,id,parent,descendants,ranking,deleted
0,None,None,None,<NA>,None,<NA>,1437599935,2015-07-22 21:18:55+00:00,story,9932359,<NA>,<NA>,<NA>,<NA>
1,None,None,None,<NA>,None,<NA>,1437599989,2015-07-22 21:19:49+00:00,story,9932362,<NA>,<NA>,<NA>,<NA>
2,None,None,None,<NA>,None,<NA>,1437600528,2015-07-22 21:28:48+00:00,story,9932423,<NA>,<NA>,<NA>,<NA>
3,None,None,None,<NA>,None,<NA>,<NA>,NaT,story,9932495,<NA>,<NA>,<NA>,<NA>
4,None,None,None,<NA>,None,<NA>,1437603233,2015-07-22 22:13:53+00:00,story,9932729,<NA>,<NA>,<NA>,<NA>

### OpenAQ

In [4]:
client = bigquery.Client(project='project-0ef0a780-55e5-435e-9d4')
df = client.get_dataset(client.dataset('openaq', project='bigquery-public-data'))

In [18]:
tables = client.list_tables(df)

In [19]:
for table in list(tables):
    print(table.table_id)

global_air_quality

In [20]:
table

In [23]:
df_openaq = client.list_rows(table, max_results=5).to_dataframe()

In [25]:
df_openaq.head()

,location,city,country,pollutant,value,timestamp,unit,source_name,latitude,longitude,averaged_over_in_hours,location_geom
0,"Borówiec, ul. Drapałka",Borówiec,PL,bc,0.85217,2022-04-28 07:00:00+00:00,µg/m³,GIOS,1.0,52.276794,17.074114,POINT(52.276794 1)
1,"Kraków, ul. Bulwarowa",Kraków,PL,bc,0.91284,2022-04-27 23:00:00+00:00,µg/m³,GIOS,1.0,50.069308,20.053492,POINT(50.069308 1)
2,"Płock, ul. Reja",Płock,PL,bc,1.41000,2022-03-30 04:00:00+00:00,µg/m³,GIOS,1.0,52.550938,19.709791,POINT(52.550938 1)
3,"Elbląg, ul. Bażyńskiego",Elbląg,PL,bc,0.33607,2022-05-03 13:00:00+00:00,µg/m³,GIOS,1.0,54.167847,19.410942,POINT(54.167847 1)
4,"Piastów, ul. Pułaskiego",Piastów,PL,bc,0.51000,2022-05-11 05:00:00+00:00,µg/m³,GIOS,1.0,52.191728,20.837489,POINT(52.191728 1)

In [29]:
query = """
        SELECT city 
        FROM `bigquery-public-data.openaq.global_air_quality`
        WHERE country = 'US'
        """
client = bigquery.Client(project='project-0ef0a780-55e5-435e-9d4')
query_job = client.query(query)

In [31]:
us_cities = query_job.to_dataframe()

/Users/tommy/.venv/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2128: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

In [ ]:
us_cities.head()

     city
0  HOWARD
1  HOWARD
2  HOWARD
3  HOWARD
4  HOWARD

In [34]:
us_cities.describe()

                           city
count                   1421351
unique                      826
top     Phoenix-Mesa-Scottsdale
freq                      39414

In [38]:
us_cities.city.value_counts().head()

city
Phoenix-Mesa-Scottsdale                     39414
Los Angeles-Long Beach-Santa Ana            27479
Riverside-San Bernardino-Ontario            26887
New York-Northern New Jersey-Long Island    25417
San Francisco-Oakland-Fremont               22710
Name: count, dtype: int64